const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'../dist');
const html=fs.readFileSync(root+'/index.html','utf8');let js=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(x=>x[1]).sort((a,b)=>b.length-a.length)[0];
const els=new Map();function el(){return {dataset:{},style:{setProperty(){}},classList:{add(){},remove(){},toggle(){},contains(){return false}},innerHTML:'',textContent:'',children:[],childNodes:[],querySelector:s=>get(s),querySelectorAll:()=>[],addEventListener(){},setAttribute(){},getAttribute(){return ''},insertAdjacentHTML(){},append(){},appendChild(){},remove(){},getBoundingClientRect(){return {top:0,bottom:0,width:100,height:100,left:0}},getContext(){return null}}}function get(s){if(!els.has(s))els.set(s,el());return els.get(s)}
const doc={getElementById:get,querySelector:get,querySelectorAll:()=>[],createElement:el,createElementNS:el,createTextNode:el,createDocumentFragment:el,addEventListener(){},documentElement:el(),body:el(),head:el()};
const context={document:doc,console,location:{hash:'',href:'',origin:'https://example.org'},navigator:{userAgent:''},history:{replaceState(){}},matchMedia:()=>({matches:true,addEventListener(){}}),addEventListener(){},requestAnimationFrame(){},cancelAnimationFrame(){},setTimeout(){},clearTimeout(){},setInterval(){},clearInterval(){},innerWidth:1400,innerHeight:900,scrollY:0,scrollTo(){},performance:{now:()=>0},IntersectionObserver:class {observe(){}unobserve(){}disconnect(){}},ResizeObserver:class{observe(){}},Image:class{},localStorage:{getItem(){return null},setItem(){}},sessionStorage:{getItem(){return null},setItem(){}},URL,URLSearchParams,fetch:()=>Promise.resolve({json:()=>({})})};context.window=context;
js=js.replace(/renderStatic\(\);\s*renderV8Static\(\);\s*renderV9Home\(\);\s*initEditor\(\);\s*tick\(\); setInterval\(tick, 20000\);/,'').replace(/route\(\);\s*$/,'');
js+='\nthis.audit={works:WORKS,notes:NOTES,renderCase,secsHTML};';
vm.createContext(context);vm.runInContext(js,context,{timeout:5000});
const missing=new Set();let count=0;for(const w of context.audit.works){context.audit.renderCase(w);let rendered=get('.js-case').innerHTML;if(!rendered.replaceAll('&amp;','&').replaceAll('&#39;',"'").replaceAll('&quot;','"').includes(w.title))throw Error('Missing title '+w.id);for(const [,src] of rendered.matchAll(/(?:src|href)="([^"#]+)"/g)){if(/^(https?:|mailto:|data:|javascript:)/.test(src))continue;const clean=decodeURIComponent(src.split(/[?#]/)[0]);if(!fs.existsSync(path.join(root,clean)))missing.add(w.id+' : '+src);count++}}
if(missing.size)process.exitCode=1;console.log(JSON.stringify({projects:context.audit.works.length,notes:context.audit.notes.length,localReferences:count,missing:[...missing]},null,2));
