import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {api,identity,published,getEntry,SEEDS,validate} from '../lib/cms/core.js';
import vm from 'node:vm';
import {publicFeed} from '../lib/cms/public-feed.js';
const sql=new DatabaseSync(':memory:');
sql.exec(readFileSync(new URL('../drizzle/0000_unique_agent_brand.sql',import.meta.url),'utf8'));
const objects=new Map();
const env={CMS_ADMIN_EMAIL:'owner@example.test',DB:{prepare(query){let args=[];const s=sql.prepare(query);return {bind(...a){args=a;return this},async first(){return s.get(...args)||null},async all(){return {results:s.all(...args)}},async run(){return {meta:s.run(...args)}}}}},BUCKET:{async put(key,body,options){objects.set(key,{body,options})}}};
let checks=0;
async function call(path,method='GET',body,auth='owner',origin='https://eeh.test'){
 const headers={};if(auth!=='anonymous'){headers['oai-authenticated-user-id']='site-owner-id';headers['oai-authenticated-user-email']=auth==='owner'?env.CMS_ADMIN_EMAIL:'viewer@example.test'}
 if(origin)headers.origin=origin;
 const request=new Request('https://eeh.test/api/cms/'+path,{method,headers,body:body instanceof FormData?body:body==null?undefined:JSON.stringify(body)});
 const r=await api(request,env);return {status:r.status,data:await r.json()};
}
const ok=(a,b)=>{assert.deepEqual(a,b);checks++};
ok((await call('entries','GET',null,'anonymous')).status,401);
ok((await call('entries','GET',null,'viewer')).status,403);
ok((await call('entries')).data.entries.length,SEEDS.length);
ok(identity(new Request('https://eeh.test',{headers:{'oai-authenticated-user-email':env.CMS_ADMIN_EMAIL}}),env),null);
const original=structuredClone(SEEDS.find(x=>x.kind==='project'));
const path='entry/'+encodeURIComponent(original.key),draft={...original,title:'수정 중인 제목'};
ok((await call(path,'PUT',{doc:draft,version:0},'owner','https://other.test')).status,403);
ok((await call(path,'PUT',{doc:draft,version:0},'owner',null)).status,403);
let result=await call(path,'PUT',{doc:draft,version:0});ok(result.status,200);ok(result.data.version,1);
ok(result.data.published.title,original.title);
ok((await published(env))[0].title,original.title);
ok((await call(path,'PUT',{doc:draft,version:0})).status,409);
const firstRevision=(await call(path+'/history')).data.items[0].id;
result=await call(path+'/publish','POST',{version:1});ok(result.status,200);ok(result.data.version,2);ok((await published(env))[0].title,draft.title);
result=await call(path,'PUT',{doc:{...draft,title:'아직 공개하지 않은 제목'},version:2});ok(result.data.version,3);ok((await published(env))[0].title,draft.title);
ok((await call(path+'/publish','POST',{version:2})).status,409);
result=await call(path+'/unpublish','POST',{version:3});ok(result.data.version,4);ok((await published(env))[0].hidden,true);
result=await call(path+'/restore','POST',{version:4,revisionId:firstRevision});ok(result.data.version,5);ok(result.data.doc.title,draft.title);ok((await published(env))[0].hidden,true);
result=await call(path+'/publish','POST',{version:5});ok(result.status,200);ok((await published(env))[0].hidden,false);
const fresh={...original,id:'test-new',key:'project:test-new',title:'새 프로젝트'};
result=await call('entry/project:test-new','PUT',{doc:fresh,version:0});ok(result.data.published,null);ok((await published(env)).some(d=>d.key===fresh.key),false);
ok((await call('entry/project:test-new/restore','POST',{version:1,revisionId:firstRevision})).status,404);
ok((await call(path,'PUT',{doc:{...draft,cover:'javascript:alert(1)'},version:6})).status,400);
ok((await call(path,'PUT',{doc:{...draft,cover:'/a" onerror="alert(1)'},version:6})).status,400);
ok((await call(path,'PUT',{doc:{...draft,links:{one:'data:text/html,hi'}},version:6})).status,400);
ok((await call(path,'PUT',{doc:{...draft,blocks:[{type:'script',text:'alert(1)'}]},version:6})).status,400);
let form=new FormData();form.append('file',new Blob(['<svg onload="alert(1)">'],{type:'image/png'}),'fake.png');ok((await call('media','POST',form)).status,400);
form=new FormData();form.append('file',new Blob([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jR6kAAAAASUVORK5CYII=','base64')]),'actual.png');
result=await call('media','POST',form);ok(result.status,200);ok(result.data.mime,'image/png');ok(objects.has('cms/'+result.data.id),true);ok((await call('media')).data.items.length,1);
ok((await call('backup')).data.entries.length,SEEDS.length+1);
const context={window:{EEH_CMS_BOOT:{docs:[fresh],preview:null}}};vm.createContext(context);vm.runInContext(readFileSync(new URL('../public/cms-content.js',import.meta.url),'utf8'),context);const cms=context.window.EEHCMS,works=[],notes=[],studio={};cms.apply(works,notes,studio);ok(works[0].heroSrc,fresh.cover);ok(works[0].sections[0].p[0],fresh.summary);
assert(!cms.blocks([{type:'p',text:'<script>alert(1)</script>'}]).includes('<script>'));checks++;
const route=readFileSync(new URL('../app/route.ts',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace("export const dynamic='force-dynamic';",'').replace('export async function GET(request:Request)','async function GET(request)');
const GET=new Function('env','html','published','getEntry','identity',route+';return GET;')(env,readFileSync(new URL('../site/index.html',import.meta.url),'utf8'),published,getEntry,identity);
let response=await GET(new Request('https://eeh.test/?cms_preview='+fresh.key));ok(response.status,403);
response=await GET(new Request('https://eeh.test/?cms_preview='+fresh.key,{headers:{'oai-authenticated-user-id':'site-owner-id','oai-authenticated-user-email':env.CMS_ADMIN_EMAIL}}));ok(response.status,200);assert((await response.text()).includes('"preview":"project:test-new"'));checks++;
response=await GET(new Request('https://eeh.test'));const html=await response.text();ok(html.includes('"key":"project:test-new"'),false);ok(response.headers.get('Cache-Control'),'no-store');
console.log(`${checks} CMS checks passed: owner authorization, origin protection, draft/public separation, version conflicts, history restore, uploads, input safety, new projects, private preview.`);

const feedDocs=await published(env);
const feed=publicFeed([...feedDocs,{kind:'note',cover:'/media/12345678-1234-1234-1234-123456789012',blocks:[{type:'p',text:'</script><script>alert(1)</script>'}]}],'https://eeh.test');
assert(!feed.includes('<script>'));
const sandbox={window:{}};vm.createContext(sandbox);vm.runInContext(feed,sandbox);
assert.equal(sandbox.window.EEH_CMS_BOOT.preview,null);
assert(!sandbox.window.EEH_CMS_BOOT.docs.some(d=>d.key==='project:test-new'));
assert.equal(sandbox.window.EEH_CMS_BOOT.docs.at(-1).cover,'https://eeh.test/media/12345678-1234-1234-1234-123456789012');
console.log('Public Pages feed excludes drafts, escapes script content and resolves uploaded media across domains.');

assert.deepEqual(validate({...original,practices:["marketing","design"]},original.key).practices,[original.div,"marketing","design"]);
assert.throws(()=>validate({...original,practices:["unknown"]},original.key));
console.log("Multiple practice classifications validated.");
