(()=>{
 const $=s=>document.querySelector(s),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let entries=[],kind='project',entry=null,dirty=false,busy=false,picked=null,mode='text',assetCallback=null,assets=[],assetLimit=32;
 const clone=x=>JSON.parse(JSON.stringify(x));
 const types={project:'PROJECT',note:'JOURNAL',site:'SITE SETTINGS'};
 function toast(t,error=false){const x=$('#toast');x.textContent=t;x.hidden=false;x.style.background=error?'#8b4033':'#233a28';clearTimeout(toast.timer);toast.timer=setTimeout(()=>x.hidden=true,4500)}
 async function api(path,options={}){const r=await fetch('/api/cms/'+path,{...options,headers:options.body instanceof FormData?{}:{'Content-Type':'application/json'}});const d=await r.json();if(!r.ok)throw new Error(d.error||'요청하지 못했습니다.');return d}
 const entryPath=()=> 'entry/'+encodeURIComponent(entry.key);
 function state(){if(!entry)return;$('#doc-title').textContent=entry.doc.title;$('#state').textContent=dirty?'수정 중 · 아직 임시 저장하지 않았습니다.':entry.published?.hidden?'게시 중단 · 임시 저장본을 편집하고 있습니다.':!entry.published?'비공개 초안':entry.version===entry.publishedVersion?'게시 완료 · 사이트에 반영됨':'공개 사이트 유지 · 임시 저장본 편집 가능';$('#state').classList.toggle('error',dirty);document.title=(dirty?'● ':'')+entry.doc.title+' · EEH 관리자'}
 function mark(){dirty=true;state()}
 function list(){const q=$('#search').value.toLowerCase();$('#list').innerHTML=entries.filter(e=>e.doc.kind===kind&&((e.doc.title||'')+' '+(e.doc.client||'')).toLowerCase().includes(q)).map(e=>`<button class="entry ${entry?.key===e.key?'active':''}" data-key="${E(e.key)}"><b>${E(e.doc.title)}</b><small>${e.published?.hidden?'게시 중단':e.published?'공개':'초안'}${e.doc.client?' · '+E(e.doc.client):''}</small></button>`).join('');$('#project-count').textContent=entries.filter(e=>e.doc.kind==='project').length;$('#note-count').textContent=entries.filter(e=>e.doc.kind==='note').length;$('#new').hidden=kind==='site';$('#new').textContent=kind==='note'?'＋ 새 노트':'＋ 새 프로젝트'}
 async function load(){entries=(await api('entries')).entries;list()}
 function field(k,label,value,multi=false){return `<label class="field"><span>${label}</span>${multi?`<textarea data-field="${k}" rows="4">${E(value)}</textarea>`:`<input data-field="${k}" value="${E(value)}">`}</label>`}
 function info(){const d=entry.doc;let h='';if(d.kind==='site'){h=field('email','문의 이메일',d.email)+field('instagram','Instagram 계정 · @ 제외',d.instagram)+field('phone','전화번호',d.phone)+field('address','주소',d.address)+field('profilePdf','회사소개서 PDF 주소',d.profilePdf)+`<p class="help">소개 문구와 서비스 설명은 ‘화면에서 수정’에서 홈페이지를 보며 바꿀 수 있습니다.</p>`}
 else{h=field('title','제목',d.title)+field('summary','소개 · 요약',d.summary,true);if(d.kind==='project')h+=field('client','클라이언트',d.client)+field('year','연도',d.year)+`<label class="field"><span>분야</span><select data-field="div">${[['brand','브랜딩'],['space','오프라인 전시·팝업'],['marketing','마케팅'],['design','디자인']].map(([v,t])=>`<option value="${v}" ${d.div===v?'selected':''}>${t}</option>`).join('')}</select></label><label class="field"><span>작업 상태</span><select data-field="status">${[['Built','실행 프로젝트'],['Proposal','제안'],['System','브랜드 시스템'],['Archive','아카이브'],['Plan','계획']].map(([v,t])=>`<option value="${v}" ${d.status===v?'selected':''}>${t}</option>`).join('')}</select></label>`+field('tags','태그 · 쉼표로 구분',(d.tags||[]).join(', '));else h+=field('date','표시 날짜',d.date)+field('tag','카테고리',d.tag)+`<label class="field"><span>연결할 프로젝트</span><select data-field="case"><option value="">선택하지 않음</option>${entries.filter(x=>x.doc.kind==='project').map(x=>`<option value="${E(x.doc.id)}" ${d.case===x.doc.id?'selected':''}>${E(x.doc.title)}</option>`).join('')}</select></label>`;
 h+=`<div class="field"><span>썸네일 이미지</span><img class="cover" src="${E(d.cover||'/images/svm-cover.jpg')}" alt="썸네일 미리보기"><input data-field="cover" value="${E(d.cover)}" aria-label="썸네일 주소"><button class="small-action" id="pick-cover">이미지 선택·업로드</button><small>썸네일은 실제 사진을 권장합니다. 상세 페이지의 도면과 3D는 유지됩니다.</small></div>`}
 if(d.kind==='project')h+=`<fieldset class="field"><legend>함께 노출할 분야</legend><small>실제 수행한 업무에 해당하는 분야를 선택하세요. 대표 분야는 항상 포함됩니다.</small>${[['brand','브랜딩'],['space','오프라인 전시·팝업'],['marketing','마케팅'],['design','디자인']].map(([v,t])=>`<label><input type="checkbox" data-practice="${v}" ${(d.practices||[d.div]).includes(v)?'checked':''}> ${t}</label>`).join('')}</fieldset>`;$('#info').innerHTML=h;document.querySelector('[data-tab=blocks]').hidden=d.kind==='site';$('#unpublish').hidden=d.kind==='site';$('#blocks-help').textContent=d.kind==='note'?'블로그처럼 제목·문단·사진·링크를 순서대로 작성하세요.':d.kind==='project'?'추가할 내용을 블록으로 작성하세요. 기존 상세 내용은 ‘화면에서 수정’으로 고칠 수 있습니다.':'사이트 공통 문구는 화면에서 수정을 이용하세요.';$('#pick-cover')?.addEventListener('click',()=>chooseAsset(url=>{d.cover=url;mark();info()}));}
 function blocks(){const names={p:'문단',h2:'제목',blockquote:'인용',image:'이미지',link:'링크'};$('#block-list').innerHTML=(entry.doc.blocks||[]).map((b,i)=>`<div class="block"><div class="block-head"><small>${String(i+1).padStart(2,'0')} / ${names[b.type]}</small><div><button data-move="-1" data-index="${i}" aria-label="위로 이동">↑</button><button data-move="1" data-index="${i}" aria-label="아래로 이동">↓</button><button data-remove="${i}" aria-label="블록 삭제">×</button></div></div>${b.type==='image'&&b.url?`<img class="cover" src="${E(b.url)}" alt="${E(b.text)}">`:''}<textarea data-block="${i}" data-prop="text" placeholder="${b.type==='image'?'이미지 설명':b.type==='link'?'링크에 표시할 이름':'내용을 입력하세요'}">${E(b.text)}</textarea>${['image','link'].includes(b.type)?`<input data-block="${i}" data-prop="url" value="${E(b.url)}" placeholder="주소">${b.type==='image'?`<button class="small-action" data-block-image="${i}">이미지 선택·업로드</button>`:''}`:''}</div>`).join('')}
 function tab(t){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));document.querySelectorAll('.tab-pane').forEach(x=>x.hidden=x.id!==t);if(t==='history')history();if(t==='pick'&&!$('#frame-wrap iframe'))action(preview);}
 function setEntry(e){entry=clone(e);entry.doc.blocks??=[];entry.doc.text??={};entry.doc.images??={};entry.doc.links??={};dirty=false;picked=null;$('#empty').hidden=true;$('#workspace').hidden=false;$('#kind-label').textContent=types[entry.doc.kind];$('#frame-wrap').innerHTML='<div class="preview-empty">미리보기를 열어 페이지에서 직접 수정할 수 있습니다.</div>';$('#picked').innerHTML='<p class="help">오른쪽 미리보기에서 항목을 선택하세요.</p>';info();blocks();tab('info');state();list()}
 async function select(key){if(busy)return;if(dirty&&!confirm('아직 저장하지 않은 수정이 있습니다. 다른 문서로 이동할까요?'))return;return action(async()=>setEntry(await api('entry/'+encodeURIComponent(key))))}
 async function save(){if(!entry)return;const local=clone(entry.doc);entry=await api(entryPath(),{method:'PUT',body:JSON.stringify({doc:local,version:entry.version})});dirty=false;state();await load();toast('임시 저장했습니다. 공개 사이트는 유지됩니다.');return entry}
 async function preview(){if(!entry)return;try{if(dirty||!entry.version)await save();const d=entry.doc,hash=d.kind==='project'?'#/work/'+d.id:d.kind==='note'?'#/notes/'+d.id:'#/';const f=document.createElement('iframe');f.title='임시 저장본 미리보기';f.src='/?cms_preview='+encodeURIComponent(entry.key)+hash;$('#frame-wrap').replaceChildren(f)}catch(e){toast(e.message,true)}}
 async function action(f){if(busy)return;busy=true;document.querySelectorAll('.actions button').forEach(b=>b.disabled=true);document.querySelectorAll('aside,.editor-grid,#assets').forEach(x=>x.inert=true);try{await f()}catch(e){toast(e.message,true)}finally{busy=false;document.querySelectorAll('.actions button').forEach(b=>b.disabled=false);document.querySelectorAll('aside,.editor-grid,#assets').forEach(x=>x.inert=false)}}
 async function publish(actionName){if(dirty||!entry.version)await save();entry=await api(entryPath()+'/'+actionName,{method:'POST',body:JSON.stringify({version:entry.version})});dirty=false;state();await load();toast(actionName==='publish'?'게시했습니다. 사이트를 새로 열면 반영됩니다.':'게시를 중단했습니다. 저장된 내용은 유지됩니다.')}
 async function history(){try{const h=await api(entryPath()+'/history');$('#history-list').innerHTML=h.items.length?h.items.map(x=>`<div class="history-item"><div>버전 ${x.version} · ${({publish:'게시',save:'임시 저장',restore:'복원',unpublish:'게시 중단'})[x.action]||x.action}<small>${E(new Date(x.created_at).toLocaleString('ko-KR'))}</small></div><button data-restore="${E(x.id)}">임시본으로 복원</button></div>`).join(''):'<p class="help">아직 저장 기록이 없습니다.</p>'}catch(e){toast(e.message,true)}}
 async function chooseAsset(cb){assetCallback=cb;assetLimit=32;$('#asset-search').value='';const existing=Object.values(window.EEH_ASSET_INDEX?.projects||{}).flat().map(a=>({url:'/'+a.src.replace(/^\//,''),name:a.caption||a.src}));try{const up=await api('media');assets=[...up.items.filter(x=>x.mime.startsWith('image/')).map(x=>({url:'/media/'+x.id,name:x.name})),...existing];renderAssets();$('#assets').showModal()}catch(e){toast(e.message,true)}}
 function renderAssets(){const q=$('#asset-search').value.toLowerCase(),list=assets.filter(a=>(a.name+' '+a.url).toLowerCase().includes(q));$('#asset-grid').innerHTML=list.slice(0,assetLimit).map(a=>`<button data-asset="${E(a.url)}"><img src="${E(a.url)}" alt="${E(a.name)}" loading="lazy"><span>${E(a.name)}</span></button>`).join('');$('#asset-more').hidden=list.length<=assetLimit}
 $('#search').oninput=list;$('#list').onclick=e=>{const b=e.target.closest('[data-key]');if(b)select(b.dataset.key)};
 document.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{kind=b.dataset.kind;document.querySelectorAll('[data-kind]').forEach(x=>x.classList.toggle('active',x===b));list()});
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
 $('#info').addEventListener('input',e=>{if(e.target.dataset.practice){entry.doc.practices=[...document.querySelectorAll('[data-practice]:checked')].map(x=>x.dataset.practice);mark();return;}const k=e.target.dataset.field;if(!k)return;entry.doc[k]=k==='tags'?e.target.value.split(',').map(x=>x.trim()).filter(Boolean):e.target.value;mark()});
 $('#block-list').addEventListener('input',e=>{if(e.target.dataset.block==null)return;entry.doc.blocks[Number(e.target.dataset.block)][e.target.dataset.prop]=e.target.value;mark()});
 $('#block-list').onclick=e=>{const b=e.target.closest('button');if(!b)return;const xs=entry.doc.blocks;if(b.dataset.remove!=null){xs.splice(+b.dataset.remove,1);mark();blocks()}if(b.dataset.move){const i=+b.dataset.index,j=i+(+b.dataset.move);if(j>=0&&j<xs.length){[xs[i],xs[j]]=[xs[j],xs[i]];mark();blocks()}}if(b.dataset.blockImage!=null)chooseAsset(url=>{xs[+b.dataset.blockImage].url=url;mark();blocks()})};
 $('#add-block').onclick=()=>{entry.doc.blocks.push({type:$('#block-type').value,text:'',url:''});mark();blocks()};
 $('#save').onclick=()=>action(save);$('#preview').onclick=()=>action(preview);$('#publish').onclick=()=>action(()=>publish('publish'));$('#unpublish').onclick=()=>action(()=>publish('unpublish'));
 $('#history-list').onclick=e=>{const b=e.target.closest('[data-restore]');if(!b)return;action(async()=>{if(dirty&&!confirm('저장하지 않은 수정을 버리고 이전 저장본을 복원할까요?'))return;setEntry(await api(entryPath()+'/restore',{method:'POST',body:JSON.stringify({revisionId:b.dataset.restore,version:entry.version})}));await load();toast('임시본으로 복원했습니다. 확인 후 게시해 주세요.')})};
 $('#new').onclick=()=>{if(busy)return;if(dirty&&!confirm('저장하지 않은 수정을 두고 새 문서를 만들까요?'))return;const id=(kind==='note'?'note-':'project-')+crypto.randomUUID().slice(0,8),d={key:kind+':'+id,id,kind,title:kind==='note'?'새 노트':'새 프로젝트',summary:'',cover:'/images/svm-cover.jpg',client:'',year:String(new Date().getFullYear()),date:new Date().toISOString().slice(0,10),tag:'Journal',case:'',div:'space',status:'Built',tags:[],blocks:[],hidden:false,text:{},images:{},links:{}};setEntry({key:d.key,doc:d,version:0,publishedVersion:0,published:null});mark()};
 $('#mobile-preview').onclick=()=>{const on=!$('#frame-wrap').classList.contains('mobile');$('#frame-wrap').classList.toggle('mobile',on);$('#mobile-preview').setAttribute('aria-pressed',on);$('#mobile-preview').textContent=on?'데스크톱 보기':'모바일 보기'};
 document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));$('#frame-wrap iframe')?.contentWindow.postMessage({type:'eeh-cms-mode',mode},location.origin)});
 window.addEventListener('message',e=>{const f=$('#frame-wrap iframe');if(e.origin!==location.origin||e.source!==f?.contentWindow)return;if(e.data?.type==='eeh-cms-ready'){f.contentWindow.postMessage({type:'eeh-cms-mode',mode},location.origin);return}if(busy||e.data?.type!=='eeh-cms-pick'||!['text','images','links'].includes(e.data.kind))return;picked=e.data;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab==='pick'));document.querySelectorAll('.tab-pane').forEach(x=>x.hidden=x.id!=='pick');$('#picked').innerHTML=`<label class="field"><span>${E(picked.label||'선택한 항목')}</span><textarea id="pick-value" rows="7">${E(picked.value)}</textarea></label>${picked.kind==='images'?'<button id="pick-image">이미지 선택·업로드</button>':''}<button class="small-action" id="pick-reset">원본으로 돌리기</button>`;$('#pick-value').oninput=()=>changePick($('#pick-value').value);$('#pick-image')?.addEventListener('click',()=>chooseAsset(url=>{$('#pick-value').value=url;changePick(url)}));$('#pick-reset').onclick=()=>{delete entry.doc[picked.kind][picked.key];mark();toast('원본 복원을 임시 저장한 뒤 미리보기를 다시 열어주세요.')}});
 function changePick(v){entry.doc[picked.kind][picked.key]=v;mark();$('#frame-wrap iframe')?.contentWindow.postMessage({type:'eeh-cms-change',kind:picked.kind,key:picked.key,value:v},location.origin)}
 $('#close-assets').onclick=()=>$('#assets').close();$('#asset-search').oninput=()=>{assetLimit=32;renderAssets()};$('#asset-more').onclick=()=>{assetLimit+=32;renderAssets()};$('#asset-grid').onclick=e=>{const b=e.target.closest('[data-asset]');if(b){assetCallback?.(b.dataset.asset);$('#assets').close()}};
 $('#asset-upload').onclick=()=>{$('#file').value='';$('#file').click()};$('#file').onchange=()=>action(async()=>{const f=$('#file').files[0];if(!f)return;const form=new FormData();form.append('file',f);toast('원본 이미지를 업로드하고 있습니다.');const x=await api('media',{method:'POST',body:form});assetCallback?.(x.url);$('#assets').close();toast('이미지를 올렸습니다. 임시 저장 또는 게시를 눌러 반영하세요.')});
 addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
 Promise.all([api('me'),load()]).then(([me])=>{$('#account').textContent=me.email;const first=entries.find(x=>x.doc.kind==='project');if(first)setEntry(first)}).catch(e=>{toast(e.message,true);$('#empty').innerHTML='<h2>관리자 계정으로 로그인해 주세요.</h2><a href="/signin-with-chatgpt?return_to=%2Fadmin" target="_top">ChatGPT로 로그인 ↗</a>'});
})();
